export enum RoleEnum {
  USER = 'user',
  BANNED_USER = 'banned_user',
  USER_UNDERVALUE = 'user_undervalue',
  USER_DECLARATION_EDITOR = 'user_declaration_editor',
  ADMIN = 'admin',
  REWRITER = 'rewriter',
  CUSTOM_SERVICE = 'custom_service',
  LOGISTICIAN = 'logistician',
  ITEM_ACCEPTOR = 'item_acceptor',
  WAREHOUSE_CEO = 'warehouse_ceo',
  WAREHOUSE = 'warehouse',
  BLOGGER = 'blogger',
  NEWS_CREATOR = 'news_manager',
  POST_CREATOR = 'post_manager',
  PORTER = 'porter',
  CONTENT_CHECKER = 'content_checker',
  ACCOUNTANT = 'accountant',
  UTILIZE_IMMUNE = 'utilize_immune',
  WALLET_EDITOR = 'wallet_editor',
  TRUSTED_BUYER = 'trusted_buyer',
  SELF_BUYER = 'self_buyer',
  SEA_MANAGER = 'sea_manager',
  PAYPAL_CHECKER = 'paypal_checker'
}
